### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bugerry87** [restorecommerce/ostorage-srv#8]
# Environment

ostorage-srv

- Ubuntu 20.04 LTS
- NPM 7.7.6
- NodeJS v14.16.0

# What was done

- Backing System is running (only!)
- Packages installed `npm install`
- Executed build `npm run build`
- Executed pretest `npm run pretest`
- Executed test `npm run test`

# Results

```
  19 passing (45s)

---------------------|---------|----------|---------|---------|------------------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------|---------|----------|---------|---------|------------------------------
All files            |   69.05 |    53.42 |   68.07 |    69.6 |
 commandInterface.js |   22.86 |    27.27 |    5.56 |   26.67 | 3-8,21-47
 service.js          |   68.76 |    52.58 |   80.28 |   68.45 | ...-1102,1112-1115,1129-1156
 utils.js            |   70.69 |    57.89 |   76.92 |      75 | 21-31,49-53
 worker.js           |   87.78 |    76.47 |   76.47 |   89.29 | 106-115
---------------------|---------|----------|---------|---------|------------------------------
```

# Error Snippits

```
s-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 13,
  region: null,
  time: 2021-03-31T03:33:58.882Z,
  requestId: '16714FF145D3D700',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 89.90215966360499
}
      ✓ should throw an error for invalid bucket request (3020ms)
      ✓ Should replace the object (3286ms)
      ✓ should delete the object
```

**Comment by Arun-KumarH** [comment]
It is as expected, this test is meant to throw an error:
```
should throw an error for invalid bucket request
```
